const en = {
  // general
  brand_name: 'Optify',
  cancel: 'Cancel',
  submit: 'Submit',
  back: 'Back',
  check: 'Check',
  download: 'Download',
  search: 'Search',
  results: 'Results',
  random: 'Random',
  domain: 'Domain',
  get_started: 'Get Started',
  read_more: 'Read More',
  create: 'Create',
  da: 'DA',
  dr: 'DR',
  seo: 'seo',
  url: 'URL',
  next: 'Next',
  previous: 'Previous',
  reset: 'Reset',
  lorem:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry' ",
  send: 'Send',
  ok: 'Ok',
  profile: 'Profile',
  sign_out: 'Sign Out',
  signing_out: 'Signing out',
  please_wait: 'Please Wait',
  add: 'Add',
  type_here: 'Type here',
  add_an_email: '+  Add An Email',
  type_your_message: 'Type your message',
  your_cooperation: 'Your Cooperation',
  your_cooperation_sent_success: 'Your Cooperation Offer Sent Successfully!',
  edit: 'Edit',
  yes: 'Yes',
  no: 'No',
  confirm: 'Confirm',
  your_campaign_type: 'Choose your campaign type',

  // header
  email_finder: 'Email Finder',
  email_verifer: 'Email Verifer',
  pricing: 'Pricing',
  outreach: 'Outreach',
  guest_post: 'Guest Post',
  link_building: 'Link Building',
  broken_link: 'Broken Link',
  my_emails: 'My emails',
  email_address: 'Email Address',

  // link building
  link_building_title:
    'Long gone are the days when getting high-quality links from authoritative websites was done manually. Although this process still contains manual part in tons of SEO agencies, having it fully automated helps you grow at record speeds. More time, more links, happier customers.',
  guest_post_outrech_title:
    'Planning to sell a guest post on your website? Or, in search of more and better guest blog post placements? A piece of cake with Optify! Automate the process of reaching out to thousands of high quality websites that accept guest posts. You just sit back in there and relax.',
  broken_link_outrech_title:
    'Optify is there for you when it comes to your white-hat, well-thought out and content-focused broken link outreach strategy. Find broken external links on other websites in your niche within minutes and reach out to lots of them at the same time due to automation. You just  get back to nap!',

  // footer
  about_us: 'About us',
  our_solutions: 'Our Solutions',
  blog: 'Blog',
  privacy_policy: 'Privacy Policy',
  terms_conditions: 'Terms and Conditions',
  follow_us: 'Follow Us On',
  footer_long_text:
    " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy.",
  copyright: 'All Rights Reserved 2020',

  // auth
  sign_in: 'Sign In',
  sign_up: 'Sign Up',
  reset_password: 'Reset Password',
  remember_me: 'Remember me',
  forgot_password: 'Forgot password  ',
  still_not_user: 'Still not a user ?',
  email: 'Email',
  email_placeholder: 'example@example.com',
  password: 'Password',
  firstname: 'First Name',
  lastname: 'Last Name',
  country: 'Country',
  city: 'City',
  c_password: 'Confirm Password',
  i_agree_to: 'I agree to',
  t_c: 'Terms and conditions',
  pass_must_include: 'Password must include',
  capital_case: 'Capital Case',
  numeric: 'Numeric',
  choose: 'Choose ...',
  sign_up_success: 'Registration successful',
  reset_password_success: 'Password successfuly changed',
  forgot_password_success: 'Password reset successful',
  check_email_for_instructions: 'Check your email for further instructions',
  verify: 'Verify',
  verifying: 'Verifying',
  successfully_verifed: 'Successfully verifed',

  // email verifer
  single_email_verifer: 'Single Email Verifer',
  bulk_email_verifer: 'Bulk Email Verifer',
  emails: 'Emails',
  emails_placeholder: 'Paste emails here seperated by comma or space ',
  paste_emails: 'Paste emails here',
  found: 'Found',
  upload_sheet: 'Upload a sheet (allowed extensions are .xlsx .xls .csv)',

  // email finder
  single_email_finder: 'Single Email Finder',
  bulk_email_finder: 'Bulk Email Finder',
  find_emails: 'Find Emails',
  sg_email_finder_placeholder: 'Paste the domain here',
  choose_whom_to_find: 'Choose Whom To Find',
  number_of_emails_per_domain: 'Number of Emails Per Domain',
  choose_prof: 'Choose a profession',
  paste_domain_here: 'Paste the domain here',
  not_found_than: 'If not found than',
  no_match: 'No match',

  // home page
  homepage: 'Homepage',
  boost_your: 'Boost Your',
  seo_rankings: 'SEO Rankings',
  with_atm_tools: 'With Our Automated Tools',
  hero_desc:
    'With automation there is no work burnout. These SEO tools will save you a bunch of resources and time. Most importantly, they will save you from boredom.',
  lorem_ipsum:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. ",
  get_target_keyword_head: 'Get that Target Keyword ',
  get_target_keyword_desc:
    'Choose the target keyword that meets your goals the most and kick-off that new Off page SEO campaign. Simply enter your domain address and let the automated tool work instead of you.',
  choose_key: 'Choose Your',
  choose_word: 'Keyword',
  easy_selection_metrics_head: 'Super-easy Selection of Metrics',
  easy_selection_metrics_desc:
    'Got the SEO metrics you plan on tracking? Choose them here and your part is done. Go take a nap somewhere: under the cherry tree or near the river. That should be your hardest decision!',
  choose_template_and_let: 'Choose Your Template and Let our Bot Do The “Talking”',
  choose_template: 'Choose a template',
  send_email: 'Send Email',
  send_email_desc:
    'Automate everything from your very first email outreach to follow-ups and other customizations. Explore your data, get insights into your link-building performance, and quickly take data-driven actions.',
  choose_way_magic: 'Choose Your Way Of Magic',
  link_building_outrech: 'Link Building Outreach',
  link_building_outrech_desc:
    'Long gone are the days when getting high-quality links from authoritative websites was done manually. Although this process still contains manual part in tons of SEO agencies, having it fully automated helps you grow at record speeds. More time, more links, happier customers',
  guest_post__outrech: 'Guest Post Outreach',
  guest_post__outrech_desc:
    'Planning to sell a guest post on your website? Or, in search of more and better guest blog post placements? A piece of cake with Optify! Automate the process of reaching out to thousands of high quality websites that accept guest posts. You just sit back in there and relax.',
  broken_link_outrech: 'Broken Link Outreach',
  broken_link_outrech_desc:
    'Optify is there for you when it comes to your white-hat, well-thought out and content-focused broken link outreach strategy. Find broken external links on other websites in your niche within minutes and reach out to lots of them at the same time due to automation. You just  get back to nap!',

  // about us.
  and_here_we_are: 'And Here We are',
  and_here_title:
    'Optify offers SEO automated tools for Search Engine Optimizers, or SEO agencies, who want to maximize their productivity by eliminating time spent on repetitive, thoughtless SEO tasks. This allows them to focus on more important and meaningful work during the day and save a huge amount of time and resources.',
  we_do_what_we_love: 'We Do What We Love,',
  we_do_what_title:
    'Optify may be software, a group of automated SEO bots, but it was built by humans who were a long time ago bored and exhausted as hell when getting through those mundane tasks, making the same actions all day long. Irritating, right? That’s how the idea of this cute lazy creature - Optie, was born! He is the god of laziness, yet a smart, supportive colleague for anyone in need of a second hand. Full of tons of creative ideas, passionate about trying new strategies and methods to achieve higher rankings and way better results.  So, how could Optie possibly waste his time on something meaningless? And we, Optifiers, for sure, could not tolerate that anymore, as his personality lives inside of many guys like us.',
  we_do_what_subtitle: 'So, let’s get started already!',
  for_the_better: 'For The Better',
  we_are_open_for_coop: 'We are open for cooperation - Let’s talk!',
  we_are_open_titile:
    'Reach out to us any time you want, with any question you have. We’ll get back to you immediately as, you know, all our doings are already automated!',
  full_name: 'Full Name',
  about_contact_name_placeholder: 'John Smith',
  about_contact_message_placeholder: 'Write your message',
  about_contact_company_placeholder: 'Apple',
  company_name: 'Company Name',
  message: 'Message',
  i_am_not_robot: 'I’m not a robot.',

  // privacy policy
  policy_section_one:
    'We are very delighted that you have shown interest in our enterprise. Data protection is of a particularly high priority for the management of the Optify. The use of the Internet pages of the Optify is possible without any indication of personal data; however, if a data subject wants to use special enterprise services via our website, processing of personal data could become necessary. If the processing of personal data is necessary and there is no statutory basis for such processing, we generally obtain consent from the data subject.',
  policy_section_two:
    'The processing of personal data, such as the name, address, e-mail address, or telephone number of a data subject shall always be in line with the General Data Protection Regulation (GDPR), and in accordance with the country-specific data protection regulations applicable to the Optify. By means of this data protection declaration, our enterprise would like to inform the general public of the nature, scope, and purpose of the personal data we collect, use and process. Furthermore, data subjects are informed, by means of this data protection declaration, of the rights to which they are entitled.',
  policy_section_three:
    'the most complete protection of personal data processed through this website. However, Internet-based data transmissions may in principle have security gaps, so absolute protection may not be guaranteed. For this reason, every data subject is free to transfer personal data to us via alternative means, e.g. by telephone.',

  // validation messages
  email_required_msg: 'Please enter an email address!',
  invalid_email_msg: 'Please enter a valid email address!',
  invalid_emails_msg: 'Please enter a valid email addresses!',
  invalid_number_msg: 'Please enter a valid number!',
  invalid_name_msg: 'Please enter a valid name!',
  invalid_url_msg: 'Please enter a valid url!',
  password_required_msg: 'Please enter the password!',
  password_min_length_msg: 'Password must be at least 8 characters long',
  invalid_password_msg: 'Please enter a valid password',
  passwords_not_equal_msg: 'Please make sure your passwords match',

  c_password_required_msg: 'Please enter the confirm password!',
  full_name_required_msg: 'Please enter a full name!',
  first_name_required_msg: 'Please enter a first name!',
  name_required_msg: 'Please enter a name!',
  url_required_msg: 'Please enter a url!',
  invalid_first_name_msg: 'Please enter a valid first name!',
  last_name_required_msg: 'Please enter a last name!',
  invalid_full_name_msg: 'Please enter a valid full name!',
  invalid_last_name_msg: 'Please enter a valid last name!',
  c_name_required_msg: 'Please enter the company name!',
  message_required_msg: 'Please enter a message!',
  city_required_msg: 'Please enter a city',
  country_required_msg: 'Please enter a country',
  invalid_country_msg: 'Please enter a valid country',

  you_must_agree: 'You must agree to continue',
  not_robot_required_msg: 'Confirm the field',
  email_not_exist: 'This email does not exist',
  verified: 'Verified',
  not_verified: 'Not verified',
  wrong_extension_msg: 'Wrong file extension',
  smth_went_wrong: 'Something went wrong',
  domain_required_msg: 'Please enter the domain',
  domains_required_msg: 'Please enter the domains',
  invalid_domain_msg: 'Please enter a valid domain',
  label_name_required_msg: 'Please enter the label name',
  invalid_date_range_msg: 'Please enter a valid date range',
  invalid_date_msg: 'Please enter a valid date',
  expiration_date_required_msg: 'Please enter an expiration date',
  invalid_city_msg: 'Please enter a valid city name',
  day_required_msg: 'Please select a day',
  required_field: 'Required field',
  invalid_range_msg: `Valid range`,
  greater_equal_than: 'Value must be greater than or equal to',
  proffesion_required_msg: 'Please choose a proffesion/s',
  main_text_required_msg: 'Please enter a main text!',
  invalid_main_text_msg: 'Main text symbols valid range  [1,200]',
  template_name_required_msg: 'Please enter a template name !',
  invalid_template_name_msg: 'Template name symbols valid range [1,50]',
  keyword_required_msg: 'Please enter a keyword !',
  invalid_keyword_msg: 'Keyword symbols valid range [1,50]',
  keyword_word_limit: 'Keyword must contain less than 4 words',
  keyword_special_symbols_msg: 'Keyword must not contain special characters',
  keyword_min_length_msg: 'Keyword symbols minimum length is 2',
  no_keyword_found: 'No keyword found',
  your_competitor_url_required_msg: 'Please enter your competitor url',
  card_number_required_msg: 'Please enter a card number',
  invalid_card_number_msg: 'Please enter a valid card number',
  streed_address_required_msg: 'Please enter a street address',
  invalid_cvv_msg: 'Please enter a valid cvv code',
  cvv_required_msg: 'Please enter a cvv code',
  building_required_msg: 'Please enter a Building/Apt address',
  invalid_zip_msg: 'Please enter a valid zip code',
  zip_required_msg: 'Please enter a zip code',

  // pricing
  pricing_plan: 'Pricing Plan',
  pricing_chuoose: 'Choose the plan which fits best to you',
  lorem_md: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  lorem_sm: 'Lorem Ipsum is simply dummy',
  pricing_get: 'Get Started',
  pricing_mouth: 'No monthly charges, pay as you go',
  pricing_email: 'Each email verification costs 1 credit.',
  pricing_credits: 'Credits do not expire. And it comes in cheap, if you buy larger plans.',
  popular: 'POPULAR',

  // blog
  blog_marketing: 'The Best Marketing Tools of 2021',
  blog_user: 'Natalie Jameson',
  blog_position: 'Search Engine Optimizer',
  find_article: 'Find the Article',
  which_interests_most: 'Which Interests You The Most',

  // article
  singl_blog: 'Boost Your SEO Rankings',
  blog_time: 'min read',
  blog_about: 'About The Author',
  blog_name: 'Natalie Portman',
  blog_article: 'All Articles',
  blog_comments: 'All Comments',
  leave_comments: 'Leave a Comment',
  comment_placeholder: 'Write your message, request or concern',
  hours: 'h ago',

  // guest post
  unsubscribers_list: 'Unsubscribers List',
  domain_metrics: 'Domain Metrics',
  traffic: 'Traffic',
  spam_score: 'Spam Score',
  page_metrics: 'Page Metrics',
  publishing_date: 'Publishing Date',
  word_count: 'Word count',
  advanced_filters: 'Advanced Filters',
  filter_traffic_country: 'Filter Traffic By Country',
  choose_whom_send: 'Choose Whom To Send',
  content_marketing_specialist: 'Content Marketing Specialist',
  choose_proffesion: 'Choose a proffesion',
  what_website_about: 'What your website is about.',
  direct_indirect_exchange: 'Is it Direct or Indirect exchange?',
  direct: 'Direct',
  direct_exchange: 'Direct Exchange',
  your_web_url: 'Your Website’s URL',
  indirect: 'Indirect',
  indirect_exchange: 'Indirect Exchange',
  see_more: 'See More',
  title: 'Title',
  add_title: 'Add Title',
  give_backlink_question: 'Would you like to give a backlink as an exchange?',
  create_new_keyword: 'Create New Keyword',
  add_keyword: 'Add Keyword',
  see_10_more: 'See 10 more',

  // broken link
  your_competitors_url: 'Your Competitor’s URL',
  your_competitor_url: 'Your Competitor URL',

  // date texts
  choose_start_date: 'Choose start date',
  choose_end_date: 'Choose end date',
  choose_date: 'Choose a date',

  // mailing
  new_campaign: 'New Campaign',
  statistics: 'Statistics',
  select_all: 'Select all',
  kanban_view: 'Kanban View',
  sent: 'Sent',
  inbox: 'Inbox',
  add_label: 'Add label',
  delete: 'Delete',
  mark_read: 'Mark as read',
  mark_unread: 'Mark as unread',
  labels: 'Labels',
  updates: 'Updates',
  label_as: 'Label as:',
  label: 'Label',
  new_label: 'New Label',
  new_name: 'New Name',
  creat_new: 'Create New',
  manage_labels: 'Manage Labels',
  oops: 'Oops!',
  no_data_found: 'No Data Found',
  choose_keywords: 'Choose Keywords',
  choose_keywoords_success: 'Choose Keywords',
  keywoord_animetion:
    '2D animation is one of the major types of animation. It’s widely used for creating animated movies, cartoons, marketing videos, advertisements, educational materials, games, and so much more.',
  keywoord_content:
    'With the rise of video content, more and more businesses consider using animated videos for promotion, as they increase conversion rates by 20%. Some companies hire animation team, the others try to create them online with the help of video maker tools.',
  subject_of_email: 'Subject of email',
  forward: 'Forward',
  reply: 'Reply',
  cooperation_finder: 'Cooperation Finder',

  // template
  template: 'Template',
  select: 'Select',
  create_your: 'Create your own',
  template_style: 'template style',
  template_name: 'Template Name',
  name_here: 'Type name here',
  main_text: 'Main Text',
  hi: 'Hi',
  name: 'Name',
  link: 'Link',
  create_new_template: 'Create New Template',

  // test emails
  test_emails: 'Test Emails',
  sending_hours: 'Sending Hours (GMT+4)',
  sending_per_minute: 'Sending Per Minute',
  sending_days: 'Sending Days',
  follow_up_days: 'Follow Up Days',
  second_follow_up_days: '2nd Follow Up Days',
  number_follow_ups: 'Number of Follow Ups',
  follow_up_after: 'Follow Up After',
  select_time: 'Select time',
  we_found: 'We found',
  potencial_cooperations: 'potential link building cooperations',
  max_emails_per_day: 'Maximum Number of Emails Per Day',
  if_words_like_unsubscribe: 'If in reply there words like',
  unsubscribe: 'unsubscribe',
  add_to_unsub_list: 'than add the email to the unsubscribe list.',
  if_email_not_found:
    'If email address is not found change the email and send to the next person from the priority list.',
  after_last_follow:
    'After the last follow up change the email and send to the next person from the priority list.',
  test_email: 'Test Email',
  test_template: 'Test Template',

  // payment details
  credit_for: 'Credit for',
  card_name_surname: 'Card - Name Surname',
  card_number: 'Card Number',
  street_address: 'Street Address',
  exp_date: 'Expiration Date',
  cvv: 'CVV Code',
  building_apt: 'Building/Apt.',
  zip: 'ZIP Code',
  save_payment_method: 'Save Payment Method',
  i_agree_with: 'I agree with',
  payment_details: 'Payment Details',
  payments_t_c: 'Payment Terms & Conditions',
  card_name_placeholder: 'Name Surname (as on card)',
  purchase_success: 'Purchase Success',
  purchase_success_title: 'Your purchase has been successfully completed!',
};

export default en;
