const SIGN_IN = 'SIGN_IN';
const SIGN_UP = 'SIGN_UP';
const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
const RESET_PASSWORD = 'RESET_PASSWORD';
const NEW_LABEL = 'NEW_LABEL';
const CHOOSE_KEYWORDS = 'CHOOSE_KEYWORDS';
const CREATE_NEW_TEMPLATE = 'CREATE_NEW_TEMPLATE';
const STATISTICS = 'STATISTICS';
const COOPERATION_FINDER = 'COOPERATION_FINDER';
const TEST_TEMPLATE = 'TEST_TEMPLATE';
const UNSUBSCRIBERS_LIST = 'UNSUBSCRIBERS_LIST';
const ADD_KEYWORD = 'ADD_KEYWORD';

// infomodals
const COOPERATION_SUCCESS = 'COOPERATION_SUCCESS';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
const NEW_CAMPAIGN = 'NEW_CAMPAIGN';

const MODALS = {
  SIGN_IN,
  SIGN_UP,
  SIGN_UP_SUCCESS,
  FORGOT_PASSWORD,
  FORGOT_PASSWORD_SUCCESS,
  RESET_PASSWORD,
  RESET_PASSWORD_SUCCESS,
  NEW_LABEL,
  CHOOSE_KEYWORDS,
  CREATE_NEW_TEMPLATE,
  STATISTICS,
  COOPERATION_FINDER,
  TEST_TEMPLATE,
  UNSUBSCRIBERS_LIST,
  COOPERATION_SUCCESS,
  ADD_KEYWORD,
  PURCHASE_SUCCESS,
  NEW_CAMPAIGN
};

export default MODALS;
